@startuml

[fastqc]
note right of [fastqc]
  - if (runFastqc=true)
  - once for each input FASTQ
endnote

component alignAndPairSlim as align
note right of [align] : sorted lane-BAMs

component mergeAndMarkDuplicatesSlim as merge
note right of [merge]
  - merge lane BAMs into merged BAM
  - variants for Picard, Biobambam and
    Sambamba
endnote

component "coveragePlot[Single]" as plot
note bottom of [plot]
  - generate a coverage plot
  - single variant called if
    only one of control & tumor
    available
endnote

component "annotateCoverageWindows" as annotate
note top of [annotate]
  estimate sample's sex
endnote

component "mergeAndFilterCovWindows" as filter

component "correctGc" as correct
note right of [correct]
  GC-bias and replication-timing
  corrected coverage
endnote


[fastqc] "2" *-down-> [align]

[align] "n" *-down-> [merge]

[merge] "1-2" *-down-> [plot]

[merge] -down-> [annotate]

[annotate] -down-> [filter]

[filter] -down-> [correct]

legend top
  Workflow structure for WGS data
endlegend

@enduml
